spring:
  application:
    name: abuba
  profiles:
    active: prod
  jwt:
    secret: spring.jwt.secret=vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

springdoc:
  swagger-ui:
    path: /swagger # Swagger UI를 표시할 커스텀 경로
  api-docs:
    path: /docs  # API 문서 경로를 커스텀

accountNo: 0010307956085451
api:
  key: 50f3e70a64074c42a5905b877ea1b194
user:
  key: 53714417-7f2c-4bed-8608-f7d39353bbd9
#security log
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.authentication: DEBUG
